---
title: "Why are you still here?"
description: |
  When society expects you to leave
author: Pratik Bhandari
date: 2024-07-31
categories:
  - life
  - "2024"
draft: false
# image: primer-timeline.svg
editor: 
  markdown: 
    wrap: sentence
tbl-cap-location: top
---

------------------------------------------------------------------------

Today, I went to a blood donation campaign. I met some old folks—I've known most of them since childhood. They are my parents' friends, friends' parents, neighbors, and school buddies. It was a refreshing and energizing social interaction, given that social gatherings aren't particularly my thing.

While my brother was lying down donating blood, I used Namaste 🙏 to renew some old relationships. There came an uncle I met a few months ago in a different context. He raised his eyebrows: “You're still here?” He looked surprised to see me here. It was unfathomable to him that someone of my age, qualifications, and background would stay in the country for many months…

The Nepali middle class aspires to emigrate to the West as if a mystical being abroad magically bestows wealth and prosperity upon landing there. If you are young and not planning to leave the country, you are tagged a failure. On the contrary, a man with a permanent residency in Australia or any European or American country becomes the most eligible bachelor in the town! Wow!

There is severe disillusionment among the youth. Folks around me who were lieutenant in the Nepal army or a branch manager at a major class-A bank quit their jobs and moved to Canada, searching for a better life. A business-owner friend of mine just sold his business last month. Next week, he is flying to Dubai. People from all walks of life are consistently deserting the country. The [data](https://www.immigration.gov.np/page/arrival-departure-report) from the Immigration Office shows that in January 2024, 142 thousand Nepali passport holders left the country while only 125 thousand returned. In June, more people left (169 thousand) and returned in lesser numbers (100 thousand)[^1]. This is sad :(

These anecdotes and numbers are just …disappointing. While I have returned to the country hoping to do [something](https://www.nccsnepal.org) and contribute to society too, sometimes I worry that the society I am talking about may not exist! (Yeah, it is a bit selfish.) This society, my society, equips its children in schools with the tools necessary to “obtain a visa” to move to the US/Europe/Australia. My society believes that you have no place in this country if you are highly educated and qualified[^2]. The same is true if you are uneducated, unskilled.

I am not leaving on a sad note. This is an optimistic memory: I had a mentor and friend, during my undergraduate years, Dr. Joshi. He used to say we may not be able to revolutionize the entire nation for the change we wish to see, but we can be the change in our own niche. Let's see how it goes :)

I’ll leave you with the following Khalil Gibran byte to ponder on in this context:

>…
But there is no other way.\
The river can not go back.\
Nobody can go back.\
To go back is impossible in existence.\
The river needs to take the risk\
of entering the ocean\
because only then will fear disappear,\
because that’s where the river will know\
it’s not about disappearing into the ocean,\
but of becoming the ocean.\
>
> -- [The River Cannot Go Back](https://www.awakin.org/v2/read/view.php?tid=2422) (Khalil Gibran)

[^1]: I am aware of the limitation of comparing two cherry-picked data points. But the social and political indicators suggest that the public sentiment to “leave” is stronger now than anytime in the recent past few years.
[^2]: This is true to a large extent. Meritocracy has its flaws and we can work on those flaws. But first, we need a system of meritocracy. Unfortunately, we lack that in our institutions!!

<!-- <strong>
<i class="bi bi-envelope-at"></i>
<a href="mailto:writer@pratikb.com">
<code>writer@pratikb.com</code></a></strong> -->

***

<div
<b style="text-align:center;">Signup to my newsletter for updates.</b>
</div>

<iframe
src="https://drpratik.substack.com/embed" width="800" height="150" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no">
</iframe>
 
