---
title: "A fresh start"
subtitle: ""
author: Pratik Bhandari
date: 2020-02-26
categories:
  - english
  - saarbruecken
  - "2020"
---

<!-- Oh, so some links brought you here. Cool.\ -->

***

we made love last night\
and slept alongside\
tipsy with few bottles of Brouwhoeve IPA\
in the warmth of each other's bosom\
dreaming a future\
&ensp;&ensp; *(a happy one I imagine)*\
together.\
\
this morning\
quite early\
earlier than usual\
she wakes up before I do\
dressed up in her new pants\
&ensp;&ensp; *(those were my gifts in her birthday last week)*\
decides to leave\
yeah, leave.\
\
she takes the first flight\
to abandon the city\
&ensp;&ensp; *(would she abandon me?*\
&ensp;&ensp; *i was a good lover – she had said last week)*\
and flies to 'her' new place\
&ensp;&ensp; *(she is already 'moving on' there,*\
&ensp;&ensp; *someone texted me)*\
while I am cold and\
still in this warm bed\
stripped\
out of the dreams, fresh ones\
we had dreamt together.\
\
I ruminate\
over\
her voice\
&ensp;&ensp; *(and fantasies i had listened to)*\
her face\
&ensp;&ensp; *(and lips i had kissed on)*\
the love\
we had and\
we made–\
this schism\
tears\
me\
apart–\
I cry\
few drops of semen. Ah.\
\
Ah.\
I start\
a New day, now\
a Fresh one\
with a scotch of whiskey–\
in the Irish pub next door\
a sixty-five-year-old pensioner\
joins me with a bottle of Backbone Splitter.\
I hate beer!

***(Bang)***

_Republished in April 2021_
