project:
  type: website
  output-dir: docs
  
  preview:
    output: _site

website:
  title: "Pratik Bhandari"
  image: "me.png"
  favicon: "me.png"
  # google-analytics: 
  open-graph: true
  twitter-card: true
  site-url: https://pratik-bhandari.github.io
  repo-url: https://github.com/pratik-bhandari/pratik-bhandari
  repo-actions: issue
  page-navigation: true
  # search:
  #   algolia:
  #     index-name: 
  #     application-id: 
  #     search-only-api-key: 
  #     analytics-events: true
  #     show-logo: true
  page-footer:
    center:
      - text: '© Pratik Bhandari'
        href: index.qmd
    right:
      - icon: twitter
        href: "https://twitter.com/prbhx"
      - icon: person-circle
        href: "https://scholar.google.de/citations?user=Y0HnEQwAAAAJ&hl=en&oi=ao"
  
  navbar:
   background: "#a6a6a6"
   logo: me.png
   title: false
   collapse-below: lg
   left:
     - text: "About"
       href: index.qmd
     - text: "News"
       href: contents/news/index.qmd
     - text: "Blog"
       href: contents/blog/index.qmd
     - text: "Art"
       menu:
         - text: "Literature"
           href: contents/literature/index.qmd
         # - text: "Gallery"
         #   href: contents/gallery/index.qmd
         - text: "Codes"
           href: contents/codes/index.qmd
   right:
     - icon: twitter
       href: https://twitter.com/prbhx
     - icon: person-circle
       href: "https://scholar.google.de/citations?user=Y0HnEQwAAAAJ&hl=en&oi=ao"

format:
  html:
    toc: true
    theme: custom.scss
      # light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    
freeze: auto

# filters:
#   - filters/include-files.lua
#   - quarto

editor: source


# format:
#   html:
#     theme: cosmo
#     css: styles.css

  # navbar:
  #   background: primary
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
