project:
  type: website
  output-dir: docs
  
preview: 
  output-file: _site

website:
  title: "Pratik Bhandari"
  image: "me.png"
  favicon: "me.png"
  # google-analytics: "G-2V3SR7RJ3H" #"UA-165918285-1"
  open-graph: true
  twitter-card: true
  site-url: https://pratik-bhandari.github.io
  repo-url: https://github.com/pratik-bhandari/pratik-bhandari
  repo-actions: issue
  page-navigation: true
  # search:
  #   algolia:
  #     index-name: 
  #     application-id: 
  #     search-only-api-key: 
  #     analytics-events: true
  #     show-logo: true
  page-footer:
    center:
      - text: '© Pratik Bhandari'
        href: index.qmd
    right:
      - icon: person-circle
        href: "https://scholar.google.com/citations?hl=de&user=Y0HnEQwAAAAJ&view_op=list_works&sortby=pubdate"
    left:
      - icon: twitter
        href: "https://twitter.com/prbhx"
  
  navbar:
   background: "#a6a6a6"
   logo: me.png
   title: false
   collapse-below: lg
   left:
     - text: "Home"
       href: index.qmd
     - text: "Scribbles"
       href: contents/literature/index.qmd
     - text: "Blog"
       href: contents/blog/index.qmd
     # - text: " "
     #   icon: person-lines-fill
     #   href: contents/contact.qmd
     # - text: "Scribbles"
     #   menu:
     #     - text: "Blog"
     #       href: contents/blog/index.qmd
     #     - text: "Literature"
     #       href: contents/literature/index.qmd
   right:
     - text: "Projects"
       href: contents/projects/index.qmd
     # - text: "Codes"
     #   href: contents/codes/index.qmd
     - text: "News"
       href: contents/news/index.qmd
     - text: "Contact"
       # icon: person-lines-fill
       href: contents/contact.qmd
     # - icon: twitter
     #   href: https://twitter.com/prbhx
     # - icon: person-circle
     #   href: "https://scholar.google.com/citations?hl=de&user=Y0HnEQwAAAAJ&view_op=list_works&sortby=pubdate"

format:
  html:
    toc: true
    theme: customFontSize.scss
    # theme:
    #   light: [united, theme.scss, customFontSize.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    
freeze: auto

editor: source

