---
title: "The joy of hunting"
description: |
  Who’d waste a bullet to drag that dolour down
author: Pratik Bhandari
date: 2020-02-08
categories:
  - english
  - saarbruecken
  - "2020"
---

<!-- Oh, so some links brought you here. Cool.\ -->

***

A dark room in some random city \
In the middle of nowhere \
There lives a man \
&ensp;&ensp; _(Just living, not alive)_\
Surely he lives there \
‘cause no one has bothered to kill him ...yet! \
\
The monotonous chore of life \
As long as he can remember \
Has made him dark \
In and out. \
\
Thank god –\
&ensp;&ensp; _(Or rather not)_\
For he was educated beyond his intelligence.\
Now in the darkness \
Somehow,\
he manages to drag through his daily chore. \
What a pity! \
\
I met him yesterday \
Such a resentful man he is – \
Complains about every single way he has been treated \
&ensp;&ensp; _(and has not been treated)_\
Every other thing he ever experienced\
&ensp;&ensp; _(and he never experienced)_\
In this middle of nowhere!\
I'd never want to see such a miserable person again. \
\
I had a gun \
&ensp;&ensp; _(But who'd waste a bullet to drag that dolour down)_\
On my way to hunting – \
Ah, what a joy it was.

_Republished in April 2021_

***

<div
<b style="text-align:center;">Signup to my newsletter for updates.</b>
</div>

<iframe
src="https://drpratik.substack.com/embed" width="800" height="150" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no">
</iframe>
 