---
title: "Nobody-s"
description: |
  Nobody-s are supposed to listen. Aren’t you Pavloved by now?
author: Pratik Bhandari
date: 2019-09-18
categories:
  - english
  - saarbruecken
  - "2019"
---

<!-- Oh, so some links brought you here. Cool.\ -->

***

^[This poem is inspired in part by Emily Dickinson's [*I'm Nobody! Who are you?*](https://poets.org/poem/im-nobody-who-are-you-260)]
Who are you?
Are you nobody?\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Yes, I am nobody.\
Oh, I am also nobody.\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  I see.\
Do you see? Really?\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	Ah hmm.\
You are nobody, I am nobody\
And we both make a pair of nobody-s\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	The world is full of nobody-s, don’t you see?\
Really? I only see somebody in everybody.\
<!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
_(Well, you said you are nobody though,_\
<!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
_Or is it I who insisted?_\
<!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
_Nevermind, nuances do not matter to nobody-s -- that’s what everybody says)_\
There is always somebody in everybody, but not me.\
I am a void -- just empty\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	Yeah, I was too\
Don't sitck your oar,\
Don’t interrupt!\
nobody-s don’t have rights to interrupt\
to speak out\
Nobody-s are supposed to listen\
Aren’t you Pavloved by now?\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	(I thought you were used to being interrupted...sigh)\
You should know that I know you are empty too: just like Me,\
ready to be filled in but the lid closed by everybody: somebody day-by-day, and nobody every day\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	Aren’t you at home with the void by now?\
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
***(silence)***


_Republished in April 2021_

***

<div
<b style="text-align:center;">Signup to my newsletter for updates.</b>
</div>

<iframe
src="https://drpratik.substack.com/embed" width="800" height="150" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no">
</iframe>
 