---
title: "Research Projects"
subtitle: ""
# author: ""
# date: ""
---

***

These are some of the works I have undertaken in the past few years.

### Language Comprehension in a Noisy Channel

I was a part of project [A4](https://sfb1102.uni-saarland.de/projects/language-comprehension-in-noisy-channel/) at the Collaborative Research Center ([SFB 1102](https://sfb1102.uni-saarland.de)) *Information Density and Linguistic Encoding* at Saarland University.
The project aims to ‘examine how noise (or the effect of reduced hearing ability) will influence language comprehension, and how natural language generation systems can adapt their output to minimize the risk of misunderstanding’.
With Prof. [Vera Demberg](https://scholar.google.de/citations?hl=en&user=l2CFSAMAAAAJ),
Prof. [Jutta Kray](https://scholar.google.de/citations?user=dEF9T0cAAAAJ&hl=en&oi=ao) and
Prof. [Dietrich Klakow](https://scholar.google.de/citations?hl=en&user=_HtGYmoAAAAJ) as the PIs of the project,
I investigated behavioural and neural correlates of the interaction between top-down predictive language processing and bottom-up auditory perceptual processing
and how 'noise in the signal' interacts with these functions.
This project also contributed to my doctoral research (Nov 2018-Dec 2022).

### COVIDiSTRESS global survey

I was a part of an international consortium of researchers who gathered together to collect data on people’s psychological response to covid-19 pandemic in 48 countries.
The [study](https://royalsocietypublishing.org/doi/full/10.1098/rsos.200589) conducted by this consortium investigated the differences in responses across countries and cultures,
and the impact of these differences in people’s behavior, their coping and trust in governments’ preventive measures.
A couple of findings of this very early study were: Those who were most concerned over the virus trusted the government measures where the policies were strict; and one of the primary factors that contributed to mental distress was the concern over a disease.
There were within and between country variations, undoubtedly.

### Predictability in Bilingual Language Processing

I conducted a research project to investigate the effect of predictability on semantic processing and metacognitive processing in Spanish-Basque bilinguals
during my Master in Cognitive Neuroscience of Language at the Basque Center on Cognition, Brain and Language (Sep 2017-Sep 2018).
In 2 experiments, I found that predictability enhanced semantic and metacognitive processing in Basque (low proficiency language) when Basque words were presented as predictable trials.
Such an effect of predictability was absent in Spanish (high proficiency language).
This research project resulted in my Master's thesis, supervised by Prof. [David Soto](https://scholar.google.de/citations?hl=en&user=7bVliAUAAAAJ).

### Executive Control in Bilinguals

I was involved in several research projects as a research intern at
Prof. [Ramesh Kumar Mishra](https://scholar.google.de/citations?user=aWaIy0sAAAAJ&hl=en&oi=ao)'s
Action Control and Cognition Lab at the Center for Neural and Cognitive Sciences, University of Hyderabad, India (Dec 2015-May 2017).

#### Sensitivity to Contextual Factors

In this [research](https://link.springer.com/article/10.1007/s41809-020-00060-7), we examined bilinguals' sensitivity to social-conversational context:
if the presence of interlocutors modulates their executive control.
We found that compared to low proficient bilinguals, high proficient bilinguals bring in higher executive control
when the context demands higher monitoring due to the presence of diverse interlocutors (i.e., those who differ in their language profile) randomly.

#### Language Proficiency and Aging

This [research](https://www.tandfonline.com/doi/abs/10.1080/13825585.2018.1562029) examined if second language proficiency modulates executive control in older adults.
We found that there was no bilingual advantage:
second language proficiency did not have any effect on executive control measures in older Telugu-English bilinguals.

### Neurodiversity

I was a speech-language pathologist for over four years in Nepal:
a student clinician for over three years, a clinical intern for a year, and then some months of independent practice.
Based on these experiences and my personal experience with autism,
I expressed concern with my co-author Mr [Pratik Khanal](https://www.researchgate.net/profile/Pratik-Khanal),
a public health expert, regarding the potential side effects of the “no cure” advocacy in [correspondence](https://doi.org/10.1016/S0140-6736(16)32176-6) to a Lancet editorial.
We argue that “no cure” could hinder care to those in need, especially in countries where health care resources are poor and the available resources are poorly distributed.

***
<!-- The goal of the project is to 'examine how noise (or the effect of reduced hearing ability) will influence l
anguage comprehension, and how natural language generation systems can adapt their output to minimize the risk of misunderstanding'. -->