---
title: "In the operating room"
description: | 
    I read his name: “Dr Truman, Anaesthesia”. I chuckle.
author: Pratik Bhandari
date: 2021-10-26
categories:
  - english
  - mainz
  - "2021"
---

<!-- Oh, so some links brought you here. Cool.\ -->

***

In a dimly lit room, I am in a bed surrounded by green people: green gowns and green masks. They talk gibberish. I understand a few words: Maya, female, 28, chest, anaesthesia, Glassman, hour. They are preparing me and waiting for Dr Glassman to arrive.

“My name is Nurse Mark. You are in the operation room. Do you understand, Miss Maya?” I nod my head. He seems to not understand. I say, “Yes.” He smiles. He moves me under two giant inverted-umbrella-like monsters. They look like a constellation of LED lights you often see in Gray’s Anatomy. Suddenly they glow, and my eyes are blinded for a moment. Dr Glassman is here.

"Hello, Maya! How are you doing?"\
"Okay. Waiting it to start and get over with. You are using local, right?"\
"Good then. You didn't want general. So."\
"I've already experienced your general anesthesia. This time I want to be awake the whole time. I want to see you operate on me. I mean, how it works."\
"Let's see if you can see. You know that there will be a drape."\
Oh crap. I'd forgotten about the drape. They hide my head.\
"Oh."\

He moves the surgical display monitor here and there. (This is fancy!) I can see my chest on it. Reminds of Dashain when after beheading a goat, men in the village would shave it off and apply turmeric powder on its body before cutting it into pieces. Betadine had made my chest look just like the goat’s yellow stomach. I still have my head intact, and Dr Glassman is not Frankenstein.

Mark arranges the drapes around me. The monitor is hidden now. All I see is Green. Anaesthesia is already doing its job – I can no longer feel my chest. A guy comes near my ear and says, “You will feel dizzy and a bit cold. I have given a medication.” I read his name: “Dr Truman, Anaesthesia”. I chuckle. Mark had opened an IV line for him in my left arm.\
Wait! Didn’t Dr Glassman just say local anaesthesia? Why would I feel dizzy? Did Truman just say I won’t be able to move? How will I breathe then? They had already put an oxygen tube in and around my nose. Am I duped into all this? God.

My head! It’s hurting now. I feel tired. Sleepy. Why are my eyelids closing? I don’t want to sleep. I just want to experience everything that happens during the operation. I am here also to remind Dr Glassman to take pictures. (He has an iPhone, better than mine.) MRI images do not satisfy the eagerness of human eyes. A piece of paper with numbers on it does not give you a complete picture. Doctors might form an image out of it, but I have to see the thing itself. Don’t you wish to see the face of your killer before he is sentenced to death? Just that you don’t survive the murder attempt, and death sentences are either not possible or are not real solutions. Still, the wish remains. Sorry, I went a bit emotional. Philosophical.\
Struggling not to close the eyelids, I ask Dr Glassman how it is going there. He doesn’t say a thing.
Loud. “Hey Doctor. I don’t want to sleep. I will sing songs. Is that okay?”\
“Hmm”\
I don’t know if he is talking to me or saying something to the other assisting doctor.

I don’t care. I can’t care. I first go with Nabin K Bhattarai: “*Khadai nakhako bish le jyudai maryo*”. Then some of Coldplay, I think. English, Nepali, Hindi all mixed up – my frustrations are spelt out then: ‘Fuck’, ‘*Muji*’, ‘*Madarchod*’, … Some ill-formed sentences to some loving motherfuckers. I get them all out. Everyone here has their own shit to care about to make the operation successful despite my practice for the audition of Nepal Idol and Himalaya Roadies.

Breathing is getting difficult. Someone is stabbing me. My chest hurts. I turn left -- the clock says 3:30. Does the anaesthesia wear off after 1 hour? When did they give the anaesthesia? It is all because I resisted sleep. People say sleep is essential. Or maybe I just dozed off due to the anaesthesia, and this is a dream. I will wake up without any pain. But what about this pain right now? Remember what Descartes said: what you feel is real. Did he really say that? Fuck Descartes. He never experienced anaesthesia. Screw all armchair philosophers who don't have any experience of altered consciousness.\

Ahhh!!! No!!! Needles on my chest.
Is Dr Glassman already sewing? I clench my fist with every penetration of the needle.
“Wow, the surgery was short!”
Nothing.
Louder. “No. It hurts!”
Nothing.
Don’t they hear me? Am I just speaking inside my head? Or am I just paralyzed? I’ll be one of those stories of patients awake during surgeries feeling all the pain but unable to speak.

I am in pain now. The pain is getting unbearable. In despair, minutes feel like an eternity. When the pain is beyond ‘unbearable’, the concept of time evaporates into the ether. It is just pain and you.


"Congratulations! We have removed the tumor." Dr Glassman removes the drape and winks with his usual "*Cancer is canceled*."\
I look down where my breast used to be. Sure, *'Cancer is cancelled.'*
