---
title: "My melanin"
subtitle: ""
author: Pratik Bhandari
date: 2021-04-09
categories:
  - english
  - saarbruecken
  - "2021"
---

<!-- Oh, so some links brought you here. Cool.\ -->

***

Beauty is in the eyes of beholder you say,\
You define beauty,\
A quality one.\
You classify beautiful,\
An attractive one.\
Disgusting is instinctive to you,\
Ugly is intuitive to you.\
Oh dear,\
Now I board\
on with your eyes.\
\
You find something off with my nose\
Are they protruded too much?\
My face screams *not enough*\
Are the eyes in the right place?\
Even my bookshelves howl my ugliness --\
I can't fetch you,\
The Book on The Bookshelf\
A hundred-paged Kamashutra.\
Oh, the kind one --\
You still\
behold me\
in your eyes.\
\
What do these beholder's eyes say,\
oh the kind one?\
&ensp;&ensp;It was not *something* that was off ?\
&ensp;&ensp;Not the bookshelves that revealed my ugliness ?\
&ensp;&ensp;Not the face that screamed *ugly* ?\
A chromatic affinity?\
All not white is what I have.\
Mud is what I am,\
Alas it disgusted you --\
Melanin in my skin.\
