---
title: |
  बेरोकटोक "छाया शिक्षा" र ब्रिजकोर्स प्रतिबन्ध
description: |
  सरकारको भड्किएको ध्यान
author: Pratik Bhandari
date: 2026-03-31
categories:
  - politics
  - Nepal
  - education
  - policy
  - "2026"
draft: false
# image: primer-timeline.svg
editor: 
  markdown: 
    wrap: sentence
tbl-cap-location: top
---

------------------------------------------------------------------------

कक्षा १० पछिको ब्रिज कोर्स आफैँले बिद्यार्थीलाई दबाब र मानसिक तनाव दिन्छ भन्ने शिक्षामन्त्रीको कुरा केहि हदसम्म जायज हुँदाहुँदै पनि उहाँको ध्यान अझै सहि ठाउँमा पुग्न नसकेको जस्तो लागेर यो टिप्पणी उठाउने लेठो कसियो।[^1]

विद्यालय चल्दाचल्दै समानान्तर रुपमा आधारभूतदेखि माध्यमिक तहसम्मका ट्युशन कक्षाहरू चल्छन्। बाह्र कक्षा, मेडिकाल, इन्जिनियरिङ्, लोकसेवा आदिको प्रवेश परिक्षाको तयारी कक्षा चल्छन्। यस्तो समानान्तर "छाया शिक्षा"[^2]ले जुनसुकै उमेरको विद्यार्थीलाई पनि भित्रैबाट मार्छ -- मानसिक रूपमा त मार्छ नै, कतिलाई आत्महत्या गर्ने स्थितिसम्म पनि पुर्‍याउँछ।

भारतको तथ्याङ्क हेर्दा कोचिङ् सेन्टर नजानेमा भन्दा जानेहरूमा बढि शैक्षिक र मानसिक दबाव र तनाव रहेको पाइयो[^3]। नजानेहरूमध्ये ३% विद्यार्थीमा तनाव र मानसिक समस्या हुन्छ भने जानेहरू मध्ये ४४% मा। प्रतिस्पर्धात्मक प्रवेश परिक्षाको तयारी गर्ने गढ मानिने भारतको कोटा भन्ने ठाउँमा सन् २०१५ मा प्रति १ लाख विद्यार्थी ९ जनाले आत्महत्या गर्थे। सन् २०२३ मा त्यो सङ्ख्या भढेर प्रति १ लाखमा २० जना पुगेको छ। हामी अनुमान गर्न सक्छौँ कति क्रूर हुन्छ प्रवेश परिक्षा र त्यसको तयारी। हाम्रोमा यति साह्रो होला-नहोला तर मानसिक स्वास्थमा पर्ने असर भिन्न पक्कै छैन। कति पटक ride sharing मा यात्रा गर्दा, लोकसेवाको तयारी गरिरहेका चालकहरू भेटिएका छन् जो part-time दिउँसो वा बेलुका एकछिन् बाइक कुदाउँछन् खर्च निकाल्नका लागि। उनीहरू तयारी कक्षा सिवाय अरू गर्दैनन्। इन्जिनियरिङ् वा मेडिकल प्रवेश परिक्षा दिनेहरूको पनि स्थिति त्यहि हो। एक किसिमको दबाव र आइसोलेसनमा छन् हजारौँ युवाहरू जसले तिनको मानसिक स्वास्थमा गम्भीर असर पारिराखेको छ। त्यो असर जिन्दगीभरि रहिरहन्छ मानिस बाँच्यो भने।

भारतको PRS Legislative Research को एक रिपोर्टमा उल्लेख भएअनुसार एउटा हेल्पर पदका लागि विद्यावारिधि गरेकाहरूसमेत गरी ६४ जनाको आवेदन परेको रहेछ, कुनै एक पटक[^4]। यस्तो अवस्थामा कोहि किन कोचिङ् सेन्टर नजाओस् प्रवेश परिक्षाको तयारी गरेर आफूलाई अब्बल बनाउन? अनि तयारी कक्षा महँगो हुँदा, पैसा तिर्न नसक्नेले के गरोस्? खाडल त बढ्ने भो नि! भारतको तथ्याङ्कको साहाराले भन्दै छु, कुरा त नेपालको पनि यहि हो फेरि! म्यादी प्रहरीमा स्नातकोत्तर पढेकाले पनि आवेदन दिए भनेर समाचार नबनेका हैनन् हाम्रोमा केहि महिना अघिसम्म[^5]।

नेपालको ट्युशनको तथ्याङ्क सहजै त भेटिनँ, तर भारतमा भने माध्यमिक र उच्च माध्यमिक तहका ७५% जति विद्यार्थीहरू ट्युशन पढ्दा रहेछन्[^4]। यसको अर्थतन्त्रमा योगदान कस्तो होला?
के छाया शिक्षामा हुने आर्थिक गतिविधिलाई नेपाल सरकारले औपचारिक अर्थतन्त्रमा जोडिसकेको छ र? म विद्यार्थी हुँदाखेरि केहि समय ट्युशन पढाउँथेँ। न्युनतम् ज्याला पाएँ कि पाइनँ? सरकारलाई कर तिरेँ कि तिरिनँ? मजस्ता अनौपचारिक शिक्षकहरू प्रशस्त थिए र छन् भन्ने कुरा शिक्षामन्त्री र अर्थमन्त्रीलाई जानकारी होला कि नहोला?
खैर, छाड्दिउँ यो कुरा अहिलेलाई। के हामीलाई थाहा नेपालमा छाया शिक्षा कति करोड, अर्बको बजार हो भनेर? आजभोलि त पुतलीसडकदेखि अनलाइनसम्म तयारी कक्षा पढाउने सेन्टरहरू थपिएको थपियै देखिन्छ। बिजुलीको पोल-पोलमा ट्युसन पढाउने शिक्षक चाहियो भनेर विज्ञापन टाँसिन्छ। साथमा "शिक्षक उपलब्ध" भन्ने अर्को चिर्कटो पनि छेउमै टाँसिएको भेटिन्छ।

छाया शिक्षालाई प्रतिबन्ध लगाउने प्रयास नभएका हैनन्। दक्षिण कोरियामा सन् १९८०तिर प्राइभेट ट्युसनमाथि प्रतिबन्ध लगाइयो, तर लक्षित नतिजा आएन र ट्युसनको अन्डरग्राउन्ड मार्केट सुरु भयो[^6]। सरकारले पछि आफ्नो निर्णय फिर्ता लिनुपर्‍यो (जुन कुरामा हाम्रा शिक्षामन्त्रीलाई अनुभव प्राप्त भयो भर्खरै)। सन् २०२३देखि भने प्रवेश परिक्षामै सुधार गर्न सुरु गरेको छ कोरियाले ताकि तयारी कक्षा पढ्नै नपरोस्। हाम्रा शिक्षामन्त्रीले भने जस्तै नै सन् २०२१ तिर चीनले पनि विद्यार्थीलाई अनावश्यक तनावबाट मुक्त गर्न भनेर नाफामूलक ट्युशनमाथि प्रतिबन्ध लगायो। तर त्यसले त झन् मज्जासँग धनी र गरिबबीचको खाडल उजागर गर्दियो। सक्ने र हुनेहरूले घरमै शिक्षक बोलाउने भए। अझ सक्नेले त देशबाहिरै गएर पनि पढे। नहुनेहरूको पहुँच घट्यो।

यसमा भारतले मध्यमार्गी बाटो लिएको देखिन्छ। उदाहरणका लागि राजस्थानले सन् २०२५मा Coaching Centres (Control and Regulation) Bill ल्यायो। यसमा मानसिक स्वास्थ्यलाई ध्यान दिनुपर्ने, पारदर्शी रूपमा शुल्क निर्धारण गर्नुपर्ने, १६ वर्षभन्दा कम उमेरकालाई भर्ना गर्न नपाईने जस्ता प्रावधान राखियो। प्रतिबन्ध त लागेन तर ट्युसन वा कोचिङ् सेन्टरलाई नियमन गर्ने प्रबन्ध मिलाइयो। 

हामीले त्यसोभए प्रतिबन्ध लगाउने कि नियमन गर्ने हो? विद्यार्थीको मानसिक स्वास्थमा परेको असरलाई ध्यान दिन कोचिङ् सेन्टर र ट्युशन बन्द गर्ने कि त्यसको आवश्यकता नै नपर्ने गरी शिक्षामा परिवर्तन गर्ने? "कोचिङ् सेन्टर नगई फलानोले नाम निकाल्यो"[^7] भन्ने समाचार किन बन्छ[^8]? यसको जड समस्या के हो? समग्र शिक्षाको पहुँचमा रहेको संरचनात्मक विभेद सम्बोधन नगरी बाहिरी सुधारले मात्रै समस्या समाधान नहोला।

एकातिर सरकारका अर्थमन्त्री निजी क्षेत्रलाई प्रोत्साहन दिने कुरा गर्नुहुन्छ, अर्कोतिर शिक्षामन्त्री निजी क्षेत्रले खोलेको व्यापारमाथि प्रतिबन्ध लगाउनु हुन्छ। यो सुसङ्गत भएन र सरकारको नीति चाहिँ के हो भन्नेबारे प्रश्न उब्जायो। भोलिका दिनमा सरकारले लिने अरू नीति र कार्यक्रममा पनि सुसङ्गति हुन्छ भनेर जनतालाई आश्वस्त पार्न जरूरी छ।

यस विषयमा मात्रै हैन, जुनसुकै कुरामा, सरकारले लिने निर्णयहरू सकेसम्म तथ्याङ्कमा आधारित हुनुपर्छ। ब्रिजकोर्समाथि प्रतिबन्ध लगाउने निर्णय लिँदा कुनै अनुसन्धानको नतिजा वा तथ्याङ्कको सहारा लिएको देखिएन, लिएको भए सर्वसाधारणलाई जानकारी दिइएनजस्तो छ। अबचाहिँ "शिक्षा सर्भे" गरेर यस क्षेत्रको समग्र अवस्थाबारे तथ्याङ्कमा आधारित जानकारी लिन सरकारलाई मेरो सल्लाह छ। यसले, बाहिरका अनुभव मात्र हैन, नीतिगत सुधारकालागि नेपालकै तथ्याङ्कमा आधारित बाटो देखाउला कि? कस्ता संरचनात्मक सुधार आवश्यक छन् भन्नेमा के सरकार स्पष्ट छ त? के के कारणले गर्दा ट्युशन र कोचिङ् लिन विद्यार्थीहरू बाध्य छन्? के हाम्रो परिक्षा प्रणालीको यसमा केहि योगदान छैन? You can't find simple solutions to complex problems. प्रश्न सोधौँ र तथ्याङ्कमा आधारित भएर नीति बनाऔँ, हतारमा हैन। परिवर्तन र सुधार दिगो चाहिएको छ।

[^1]: [ब्रिजकोर्स बन्द गर्ने निर्णय](https://kantipurtv.com/education/2026/03/30/1774880905.html)
[^2]: [A review of shadow education](https://bonoi.org/index.php/sief/article/view/720)
[^3]: [Mental Health Conditions and Suicide Among Adolescent Coaching Aspirants: Case of Kota, India](https://journals.sagepub.com/doi/10.1177/09731342251359022)
[^4]: [PRS State Legislative brief](https://prsindia.org/files/bills_acts/bills_states/rajasthan/2025/Legislative_Brief_Rajasthan_Coaching_Centres_(Control_and_Regulation)_Bill_2025.pdf)
[^5]: [म्यादी प्रहरीमा युवाको आकर्षण, मास्टर्स डिग्री गरेकादेखि पूर्व प्रहरीसम्मले दिए आवेदन](https://bizmandu.com/content/20220328130514.html)
[^6]: [1980s Ban](https://www.washingtonpost.com/archive/opinions/2000/05/28/youll-never-guess-what-south-korea-frowns-upon/0649872a-61ce-402d-8687-c440e222ba2f/)
[^7]: [महाेत्तरीका महादेव पासमान](https://www.nayashiksha.com/content/829)
[^8]: [कञ्चनपुरका ललित सार्की](https://shilapatra.com/detail/129066)

<!-- <strong>
<i class="bi bi-envelope-at"></i>
<a href="mailto:writer@pratikb.com">
<code>writer@pratikb.com</code></a></strong> -->

***

<div
<b style="text-align:center;">Signup to my newsletter for updates.</b>
</div>

<iframe
src="https://drpratik.substack.com/embed" width="800" height="150" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no">
</iframe>
 
