---
title: "सत्ताको सौन्दर्यचेत"
description: |
  लोककल्याणकारी प्रेमीको बयानमा पिम्पलको उपचारविधि
author: Pratik Bhandari
date: 2026-05-01
categories:
  - nepali
  - kathmandu
  - "2026"
  # - essay
draft: false
---

<!-- Oh, so some links brought you here. Cool.\ -->

***

मलाई ऊ हाँसेको हेर्न औधी मन छ। म चाहन्छु उसको मुस्कान मीठो होस्। रूपमा निखार आओस्। तर उसको सुन्दरतामा पिम्पलले आँच पुर्‍याउँछ। त्यसलाई निचोरेर मात्र पुग्दैन। सियोले घोचेर फुटाऔँला। हो, उसलाई थोरै पीडा त हुन्छ। तर क्षणिक। सहला। अलिकति छट्पटिएर कुद्ला। समातौँला। “नाईँ” भनेछ भने पनि धागो छँदै छ सियोमा उन्‍ने। बस्, अब केहि वर्ष घोटिएर उसको मुस्कानमा निखार ल्याउने हो।

अस्तिन मैले मल्हम लगाइदिने वाचा गर्‍याथेँ रे? के भो त? मल्हमले काम गर्दैन भन्‍ने कुरा धेरैले बुझ्दैनन् हिजोआज, न उसले नै बुझ्यो! अनि फेरि, मल्हम लगायो भने त त्यसले उसको मुस्कानमा ग्रहण लगाइदिन्छ। सबै डाँडाहरू सेता बन्छन्। मल्हम लगाएको अनुहार देख्‍नुभाको छ कहिल्यै? म चाहन्‍नँ ऊ हाँस्दा सबैको ध्यान ती सेता धब्बाहरूमा जाउन्। त्यसैले, अब उसको पिम्पल फुटाइदिने हो। सिधै। सियोले।

अनि त ऊ हाँस्दा पिम्पलको ठाउँमा डिम्पल बस्छ! आहा!

तपाईँ मलाई गाली गर्नुहोला उसको गालाको पिम्पल उसलाई नसोधी हटाउन पाइँदैन भनेर। तपाईँ भन्‍नुहोला पिम्पललाई सियोले घोच्ने हैन बरू अरू नै उपचार खोज्ने हो भनेर। तपाईँ अझै थप्‍नु पनि होला पिम्पल फुटाउँदैमा डिम्पल त्यति सजिलै बस्दैन। बरू उल्टै उसलाई पीडा हुन्छ भन्‍नुहोला। एउटा उपचारको अनुमति लिएर अर्को गरेकोमा पनि तपाईँको प्रश्‍न होला। तपाईँलाई डिम्पलको साटो पिम्पल नै मन पर्छ होला।

म भन्छु तपाईँमा सौन्दर्यचेत नै छैन। साँच्‍चै तपाईँका यी सब प्रश्‍न, तर्क र कथित चिन्ताहरू वाइयातका छन्। कुनैमा दम छैन। बरू ऊ हाँसेको हेर्न चाहने मेरो असल नियतमा प्रश्‍न उठाएर तपाईँ गल्ती गर्दै हुनुहुन्छ!

हो, उसले मलाई मल्हम लगाउन अनुमति दिएको हो। तर बुझ्नुस् कि आफूलाई कस्तो उपचार चाहिन्छ भनेर जान्‍न ऊ अबोध छ। म जान्‍ने भएर त उसले मलाई छानेको हो उपचार गर्न! कसरी उसको हाँसो खुल्छ भन्‍नेबारे मैले भन्दा राम्रो निर्णय कसले गर्न सक्ला र? आखिरमा महिनौँदेखि मैले बेलुन फुटाउँदै आ’छु, रातो होस् कि हरियो। निलो नै किन नहोस्। मल्हम लगाएर उपचार हुन्थ्यो भने त अहिलेसम्म अरूले गरिसक्थे। त्यसैले बाध्य भएर मैले उसका रंगी-बिरंगी पिम्पलहरूमा घोच्नैपर्छ। कल्पना गर्नोस् त, अनुहारका सबै पिम्पल फुटाएर डिम्पलै डिम्पल आएपछि उसलाई कति सुन्दर देखिन्छ! उसका दाँत छैनन् त के भो? दाँतले कसलाई रम्‍र्‍याएको छ र अहिलेसम्म? दाह्‍रा मात्र! अनुहारको डिम्पलले न हो मुस्कान र हाँसोमा निखार ल्याउने।

सौन्दर्यचेत नहुँदासम्म बस् तपाईँ यी नमीठा प्रश्‍नले मेरो बाटो छेक्‍न छाड्नोस्। बरू लेख्‍नोस् उसका मीठा मुस्कानका बारे। बोल्नोस् सबैथोक मिलेको उसका हाँसोका बारे।
उसको पिम्पल घोच्ने सियोले, तिम्रो के के सिलाउन सक्ला?

***

<div
<b style="text-align:center;">Signup to my newsletter for updates.</b>
</div>

<iframe
src="https://drpratik.substack.com/embed" width="800" height="150" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no">
</iframe>
 