---
title: "What's in the news?"
subtitle: |
  Work/life updates
# author: ""
# date: ""
---

***

* **November 10**: I submitted my dissertation to the 5-member thesis committee a few weeks ago. The defense will very likely be held on 7 December.\
Alongside the preparation for my defense, I am also in the job market looking for a post-doc or an appropriate industry position! Look out for my applications ;)

* **July 24**: I will present two posters at the Architectures and Mechanisms for Language Processing ([AMLaP](https://amlap2022.york.ac.uk)) conference. It'll take place in York, England, September 7-9. One poster is about the recent publication on attention-prediction interplay. The second one is about the role of speech rate in the interaction of top-down and bottom-up processes in degraded speech comprehension. 

* **July 22**: Our [paper](https://mfr.osf.io/render?url=https%3A%2F%2Fosf.io%2Fdownload%2Ftdvhs%2F%3Fdirect%3D%26mode%3Drender) on the role of attention to context in understanding degraded speech is published in *Language and Cognition*[.](https://doi.org/10.1017/langcog.2022.16) Cheers!

* **June 14**: Earlier this month, I attended the [IMPRS conference](https://www.mpi.nl/imprs-conference) at the Max Planck Institute for Psycholinguistics at Nijmegen in the Netherlands. I presented a [poster](https://mfr.osf.io/render?url=https%3A%2F%2Fosf.io%2Fdownload%2Fkdpae%2F%3Fdirect%3D%26mode%3Drender) discussing the results of the experiments in which we found that a decrease in the speech rate does not amplify the [predictability effect](https://www.frontiersin.org/articles/10.3389/fpsyg.2021.714485/full) in degraded speech comprehension.

<!--* **April 18**: I can't attend the APS convention. Don't get me started about the hectic visa procedure. 2 months notice is not enough, APS! There are similar problems in other conferences organized in the USA. People have tweeted about it. See [this](https://twitter.com/ProfSomashekhar/status/1509430243412496388?s=20&t=hIB7IwHWHlxVPeDTlIXsew),
[this](https://twitter.com/imtryam/status/1508841089834549248?s=20&t=hIB7IwHWHlxVPeDTlIXsew) and
[this](https://twitter.com/bkhmsi/status/1504954744250372096?s=20&t=hIB7IwHWHlxVPeDTlIXsew),
for example.
Do you see a pattern? Humans are pattern seeking (and finding) animals collectively as a nation too.-->

* **April 14**: Our work on *the effect of speech rate on degraded speech comprehension* has been accepted for poster presentation at the IMPRS Conference [2022](https://www.mpi.nl/imprs-conference) to be held at MPI Psycholinguistics (Nijmegen, Netherlands) in June 01-03. A manuscript is cooking as well [;](bhandari2022speechrate.pdf))

* **March 09**: Our work on *the role of attention on degraded speech comprehension* has been accepted for poster presentation at the APS Annual Convention [2022](https://www.psychologicalscience.org/conventions/2022-aps-annual-convention) in Chicago in May 26-29.